<?xml version="1.0" encoding="UTF-8"?>
<project name="Simple Applet" default="build-applet" basedir=".">

	<!-- <get src="https://github.com/martinpaljak/ant-javacard/releases/latest/download/ant-javacard.jar" dest="." skipexisting="true"/> -->
	<taskdef name="javacard" classname="pro.javacard.ant.JavaCard" classpath="ant-javacard.jar"/>

    <description>Simple Applet</description>

    <target name="build-applet" description="generate the distribution">
        <tstamp/>
        <javacard jckit="./libraries/jc304_kit">
            <cap aid="A0:00:00:00:84" output="dist/SimpleApplet.cap" sources="src" version="1.0">
                <applet class="simple.applet.SimpleApplet" aid="A0:00:00:00:84:53:69:6D:70:6C:65:41:70:70"/>

                <import jar="/home/telman/develop/_JavaCard-dev/libutils/dist/libutils.jar"/>
            </cap>
        </javacard>
    </target>

    <target name="clean" description="Delete previously built applet">
        <delete dir="dist/"/>
    </target>

</project>
